root_dir : datasets/ISBI2016
train_dir : training
train_label_file : train_label.csv
test_dir : testing
test_label_file : test_label.csv
dimensions : [224, 224]
channels : 3
n_classes : 2
batch_size : 16
epochs : 10
learning_rate : 0.001
momentum : 0.9
save_model_path : models/Q1_trained

